### ISSUE TITLE
Memory conflict $308170 (PC 0x180170) used for two purposes

### ISSUE THREAD

**Issue by KevinCathcart** [mmxbass/z3randomizer#12]
That memory location is used by .GanonPyramidRespawn and the third byte of .HardModeExclusionCapeUsage.

Please reassign the GanonPyramidRespawn to a new address that does not conflict with anything.
 (It is the better one to move, as in practice only EntranceRandomizer is affected.  VT always writes the default value here, which happens to act as the correct default for the respawn too).

It is actually a bit surprising in retrospect that this was not the cause of the pyramid respawn bug you fixed a month ago.

**Comment by sporchia** [comment]
good catch, I'll move this and get in touch with ER people to update
