### ISSUE TITLE
Analysis of bunny beam permabunny issue

### ISSUE THREAD

**Issue by KevinCathcart** [mmxbass/z3randomizer#14]
Issue originally reported as sporchia/alttp_vt_randomizer#201

Here is what happens: If you are hit by a bunny beam you get turned into a bunny, the player state variable $5D is changed to indicate that you are in a temporary bunny state (set to #$1C), and a countdown timer is started for turning back. When the timer reaches zero you are changed back from a bunny and restored to the normal player state (set to #$00).

If you do anything that changes your player state state while a temporary bunny (this includes: getting knocked back due to hitting an enemy, getting zapped, jumping off a ledge, falling into a pit, or fake flippering?) the game will replace the player state with a different one. When it comes time to return to a normal state (i.e. You stop getting knocked back, you land, you recover from falling, or return to dry land), the game sees that you are a bunny and has to decide if you are a temporary bunny or a permanent one.

It bases this decision on if you have the moon pearl. If you don't have the moon pearl but are a bunny, it assumes you need to return to permabunny state. If you do have the moon pearl you must be only a temporary bunny. That logic works perfectly fine if bunny beams only exist in the dark world.

But if Enemizer or Entrance Randomizer makes them occur in the light world that check is not sufficient. In that case the game also needs to check if you are in the light world. If so then you are obviously only a temporary bunny.

Notes for Karkat: The code that decides which bunny state (temporary or permanent) you should return to is the following (lines 2417-2425 in bank07.asm):

        LDX.b #$17
        
        ; change to permabunny b/c we don't have a moon pearl
        LDA $7EF357 : BEQ .changeLinkMode
        
        LDX.b #$1C
        
        ; otherwise assume that he's a temp bunny
        BRA .changeLinkMode
That LDA $7EF357 seems like it might be an ideal line to patch. One possible approach would be to have it JSL to a subroutine that sets the Zero flag if we are in dark world without moon pearl, and clears it otherwise.

**Comment by KatDevsGames** [comment]
Fixed in trunk using the suggested method.
