### ISSUE TITLE
ZSNES Detection Splash Screen

### ISSUE THREAD

**Issue by qwertymodo** [mmxbass/z3randomizer#17]
I need to take another look at the color generation tomorrow, there are some random black pixels where they shouldn't be, but this basically works, and should be compatible with existing free space (I checked against Enemizer as well, but not any other related mods).

~~[zsnes.asm.txt](https://github.com/mmxbass/z3randomizer/files/1648658/zsnes.asm.txt)~~

**Comment by qwertymodo** [comment]
Hmm... wait, that's bugging out now in the non-ZSNES codepath.  It was working 10 minutes ago.  I think I need sleep and I'll fix it tomorrow.

**Comment by qwertymodo** [comment]
Ok, here we go.  Fixed the color issues, and I moved the data out to a later bank.  This should be good to go.  This includes the hook (it's something like 20 instructions after boot, so I think that fits your goal of "right away"), the detection code, and the display code, just patch and go.

~~[zsnes.asm.txt](https://github.com/mmxbass/z3randomizer/files/1650260/zsnes.asm.txt)~~

Edit: oops, I moved it out to the end of the 3MB region because I was using an Enemizer base ROM, moved it back into the 2MB region.
~~[zsnes.asm.txt](https://github.com/mmxbass/z3randomizer/files/1650324/zsnes.asm.txt)~~

Edit again: I was shown the list of reserved banks, so I've adjusted the location again.  This is now fully contained in banks $37 and $38.
[zsnes.asm.txt](https://github.com/mmxbass/z3randomizer/files/1650342/zsnes.asm.txt)

**Comment by KatDevsGames** [comment]
Added in trunk.
