### ISSUE TITLE
VRAM corruption/crashes when entering shops

### ISSUE THREAD

**Issue by Bonta0** [mmxbass/z3randomizer#72]
Some people are reporting issues when entering shops modified by the randomizer, they'll randomly crash or corrupt vram (about 1/4 chance), vanilla shops do not have that issue
The code responsible for this is the DMA at https://github.com/KatDevsGames/z3randomizer/blob/d182c3343efaf5292b0b3b3ea284d9e77aaa19c2/shopkeeper.asm#L207
Moving that to the NMI hook fixes this issue

**Comment by KatDevsGames** [comment]
Fixed in current dev build.
