### ISSUE TITLE
Items that share a slot aren't displayed on file select screen until after you save & quit once

### ISSUE THREAD

**Issue by oneup40** [mmxbass/z3randomizer#74]
Steps to reproduce: Make a customizer seed that has a blue boomerang in the initial inventory. Load the generated ROM in an emulator. Create a new savefile in game. The file select item tracker won't show your blue boomerang. Start the savefile to check that you actually do have the blue boomerang. Save and quit, and the file select item tracker now properly shows your blue boomerang.

https://www.twitch.tv/oneup40/clip/MildManlyDadFutureMan

The inventory item swap patch and file select item tracker patch use extra bytes at offsets 0x3c and 0x3e in the SRAM inventory to track the state of swappable items, but the original game code doesn't know about these extra bytes when it initializes a new savefile (https://github.com/walkingeyerobot/alttp-disassembly/blob/master/Bank0C.asm#L3646)

Rom::setStartingEquipment in app/Rom.php in the other Github will likely need to be updated too when this is fixed.

**Comment by JonHanon** [comment]
https://github.com/KatDevsGames/z3randomizer/pull/75/
This should fix it?

**Comment by KatDevsGames** [comment]
Fixed in current dev build.
