### ISSUE TITLE
Total Item Locations Not Updated in Zora's Domain

### ISSUE THREAD

**Issue by intcounter** [mmxbass/z3randomizer#9]
The "Total Item Locations Checked" statistics, 0x423, does not appear to be updating nor counting items obtained in Zora's Domain. For example, tested with Seed 867152751 (no glitches, 26, normal, standard, gannon), I observed the following:
- pick up the second chest in the Waterfall of Wishing; 0x423 increases to 11
- pick up the ledge item in Zora's Domain: 0x423 remains constant
- pick up the item from under the bridge (another special area): 0x423 increases to 12

**Comment by KatDevsGames** [comment]
Fixed in current dev build.
