### ISSUE TITLE
Killing aga2 in fake dark world changes to real dark world in rom_mode OverworldGlitches (non-vanilla behavior)

### ISSUE THREAD

**Issue by krelbel** [mmxbass/z3randomizer#97]
Killing aga1 (who spawns instead of aga2 if aga1 wasn't defeated) at the top of GT in the practice hack after dying in GT sends you to the pyramid in fake dark world as expected.  In the randomizer, with a seed generated without the patch disabling fake dark world (OWG, for example), killing aga2 at the top of GT after dying in GT (having not killed aga1) sends you to the real dark world.  This seems like unexpected behavior, and potentially a bug in the randomizer baserom patch.

**Comment by krelbel** [comment]
Note that this bug appears to be exclusive to rom_mode: OverworldGlitches and not rom_mode: MajorGlitches.  

https://alttpr.com/en/h/z6GKqgELve OWG customizer seed in which killing aga2 after dungeon revival sends you to the real dark world (buggy behavior; it should send you to fake dark world)

https://alttpr.com/en/h/KJG3BmQJy3 Same customizer settings, except changed rom_mode from OverworldGlitches to MajorGlitches; in this seed, killing aga2 after dungeon revival sends you to fake dark world (as expected).

**Comment by tcprescott** [comment]
this is set in the PHP, this issue should be transferred to https://github.com/sporchia/alttp_vt_randomizer

**Comment by krelbel** [comment]
On further consideration you're absolutely right (changing this in the baserom would also change this behavior for ER, and we definitely want this behavior in ER).  Opened https://github.com/sporchia/alttp_vt_randomizer/issues/907 and closing this issue here.
